from typing import Protocol
import uuid
from app.domain.entities.login_history import LoginHistory

class LoginHistoryRepository(Protocol):
    async def create(self, history: LoginHistory) -> LoginHistory: ...
    async def list_by_user(self, user_id: uuid.UUID, skip: int = 0, limit: int = 100) -> tuple[list[LoginHistory], int]: ...
    async def get_today_login_count(self) -> int: ...
    async def get_today_failed_login_count(self) -> int: ...
