from typing import Protocol
import uuid
from app.domain.entities.refresh_token import RefreshToken

class RefreshTokenRepository(Protocol):
    async def create(self, token: RefreshToken) -> RefreshToken: ...
    async def get_by_token(self, token: str) -> RefreshToken | None: ...
    async def update(self, token: RefreshToken) -> RefreshToken: ...
    async def revoke_all_for_user(self, user_id: uuid.UUID) -> None: ...
