from typing import Protocol
import uuid
from app.domain.entities.user_session import UserSession

class SessionRepository(Protocol):
    async def create(self, session: UserSession) -> UserSession: ...
    async def get_by_id(self, session_id: uuid.UUID) -> UserSession | None: ...
    async def get_by_refresh_jti(self, jti: str) -> UserSession | None: ...
    async def list_by_user(self, user_id: uuid.UUID) -> list[UserSession]: ...
    async def update(self, session: UserSession) -> UserSession: ...
    async def delete(self, session: UserSession) -> None: ...
    async def revoke_all_for_user(self, user_id: uuid.UUID) -> None: ...
    async def get_active_sessions_count(self) -> int: ...
