from typing import Protocol
import uuid
from app.domain.entities.user import User
from app.domain.enums.user_status import UserStatus

class UserRepository(Protocol):
    async def get_by_id(self, user_id: uuid.UUID) -> User | None: ...
    async def get_by_email(self, email: str) -> User | None: ...
    async def get_by_username(self, username: str) -> User | None: ...
    async def list_users(self, skip: int = 0, limit: int = 100, search: str | None = None) -> tuple[list[User], int]: ...
    async def create(self, user: User) -> User: ...
    async def update(self, user: User) -> User: ...
    async def delete(self, user: User, deleted_by: uuid.UUID | None = None, delete_reason: str | None = None) -> None: ...
    async def restore(self, user_id: uuid.UUID, restored_by: uuid.UUID | None = None) -> User | None: ...
    async def bulk_update_status(self, user_ids: list[uuid.UUID], status: UserStatus, updated_by: uuid.UUID | None = None) -> None: ...
    async def get_total_count(self) -> int: ...
    async def get_active_count(self) -> int: ...
    async def get_locked_count(self) -> int: ...
