"""enterprise_auth_module

Revision ID: 109807a03631
Revises: bd0eb6cd646c
Create Date: 2026-07-13 19:19:57.067405

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '109807a03631'
down_revision: Union[str, Sequence[str], None] = 'bd0eb6cd646c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Create Enums manually
    permission_module_enum = postgresql.ENUM('AUTH', 'USERS', 'ROLES', 'DRIVERS', 'TRACTORS', 'TRIPS', 'INVOICES', 'MAINTENANCE', 'FUEL', 'REPORTS', 'SETTINGS', name='permission_module', create_type=True)
    permission_module_enum.create(op.get_bind(), checkfirst=True)
    
    audit_action_enum = postgresql.ENUM('LOGIN', 'LOGOUT', 'CREATE', 'UPDATE', 'DELETE', 'RESTORE', 'PASSWORD_CHANGE', 'PERMISSION_CHANGE', name='audit_action', create_type=True)
    audit_action_enum.create(op.get_bind(), checkfirst=True)
    
    user_status_enum = postgresql.ENUM('ACTIVE', 'INACTIVE', 'LOCKED', 'PENDING_VERIFICATION', name='user_status', create_type=True)
    user_status_enum.create(op.get_bind(), checkfirst=True)

    op.create_table('login_history',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.String(length=512), nullable=True),
    sa.Column('device_fingerprint', sa.String(length=255), nullable=True),
    sa.Column('browser', sa.String(length=100), nullable=True),
    sa.Column('os', sa.String(length=100), nullable=True),
    sa.Column('platform', sa.String(length=100), nullable=True),
    sa.Column('result', postgresql.ENUM('SUCCESS', 'FAILED_BAD_CREDENTIALS', 'FAILED_LOCKED', 'FAILED_INACTIVE', name='login_result'), nullable=False),
    sa.Column('failure_reason', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('clock_timestamp()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('clock_timestamp()'), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('delete_reason', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('version_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_login_history_user_id'), 'login_history', ['user_id'], unique=False)
    op.create_table('password_history',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('clock_timestamp()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('clock_timestamp()'), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('delete_reason', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('version_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_password_history_user_id'), 'password_history', ['user_id'], unique=False)
    op.create_table('user_preferences',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('theme', sa.String(length=50), nullable=False),
    sa.Column('language', sa.String(length=10), nullable=False),
    sa.Column('timezone', sa.String(length=50), nullable=False),
    sa.Column('date_format', sa.String(length=20), nullable=False),
    sa.Column('number_format', sa.String(length=20), nullable=False),
    sa.Column('dashboard_layout', sa.String(length=255), nullable=False),
    sa.Column('notification_settings', sa.String(length=1000), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('clock_timestamp()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('clock_timestamp()'), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('delete_reason', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('version_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('user_sessions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('device_fingerprint', sa.String(length=255), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.String(length=512), nullable=True),
    sa.Column('refresh_token_jti', sa.String(length=255), nullable=True),
    sa.Column('status', postgresql.ENUM('ACTIVE', 'REVOKED', 'EXPIRED', name='session_status'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('clock_timestamp()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('clock_timestamp()'), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('delete_reason', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('version_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_sessions_refresh_token_jti'), 'user_sessions', ['refresh_token_jti'], unique=False)
    op.create_index(op.f('ix_user_sessions_user_id'), 'user_sessions', ['user_id'], unique=False)
    op.add_column('audit_logs', sa.Column('module', postgresql.ENUM('AUTH', 'USERS', 'ROLES', 'DRIVERS', 'TRACTORS', 'TRIPS', 'INVOICES', 'MAINTENANCE', 'FUEL', 'REPORTS', 'SETTINGS', name='permission_module'), nullable=False))
    op.alter_column('audit_logs', 'action',
               existing_type=sa.VARCHAR(length=10),
               type_=postgresql.ENUM('LOGIN', 'LOGOUT', 'CREATE', 'UPDATE', 'DELETE', 'RESTORE', 'PASSWORD_CHANGE', 'PERMISSION_CHANGE', name='audit_action'),
               existing_nullable=False,
               postgresql_using="action::audit_action")
    op.add_column('drivers', sa.Column('delete_reason', sa.String(length=255), nullable=True))
    op.add_column('expense_categories', sa.Column('delete_reason', sa.String(length=255), nullable=True))
    op.add_column('expenses', sa.Column('delete_reason', sa.String(length=255), nullable=True))
    op.add_column('fuel_histories', sa.Column('delete_reason', sa.String(length=255), nullable=True))
    op.add_column('fuel_transactions', sa.Column('delete_reason', sa.String(length=255), nullable=True))
    op.add_column('fuel_vendors', sa.Column('delete_reason', sa.String(length=255), nullable=True))
    op.add_column('invoice_payment_history', sa.Column('delete_reason', sa.String(length=255), nullable=True))
    op.add_column('invoice_payments', sa.Column('delete_reason', sa.String(length=255), nullable=True))
    op.add_column('invoice_status_histories', sa.Column('delete_reason', sa.String(length=255), nullable=True))
    op.add_column('invoices', sa.Column('delete_reason', sa.String(length=255), nullable=True))
    op.add_column('maintenance_history', sa.Column('delete_reason', sa.String(length=255), nullable=True))
    op.add_column('maintenances', sa.Column('delete_reason', sa.String(length=255), nullable=True))
    op.add_column('materials', sa.Column('delete_reason', sa.String(length=255), nullable=True))
    op.add_column('notifications', sa.Column('delete_reason', sa.String(length=255), nullable=True))
    op.add_column('parties', sa.Column('delete_reason', sa.String(length=255), nullable=True))
    op.add_column('payments', sa.Column('delete_reason', sa.String(length=255), nullable=True))
    op.add_column('permissions', sa.Column('name', sa.String(length=100), nullable=True))
    op.execute('UPDATE permissions SET name = code')
    op.alter_column('permissions', 'name', nullable=False)
    
    op.add_column('permissions', sa.Column('module', postgresql.ENUM('AUTH', 'USERS', 'ROLES', 'DRIVERS', 'TRACTORS', 'TRIPS', 'INVOICES', 'MAINTENANCE', 'FUEL', 'REPORTS', 'SETTINGS', name='permission_module'), nullable=False, server_default='USERS'))
    op.add_column('permissions', sa.Column('delete_reason', sa.String(length=255), nullable=True))
    op.drop_index(op.f('ix_permissions_code'), table_name='permissions')
    op.drop_index(op.f('uq_permissions_code'), table_name='permissions', postgresql_where='(deleted_at IS NULL)')
    op.create_index(op.f('ix_permissions_name'), 'permissions', ['name'], unique=False)
    op.create_index('uq_permissions_name', 'permissions', ['name'], unique=True, postgresql_where='deleted_at IS NULL')
    op.drop_column('permissions', 'code')
    op.add_column('quarries', sa.Column('delete_reason', sa.String(length=255), nullable=True))
    op.add_column('roles', sa.Column('delete_reason', sa.String(length=255), nullable=True))
    op.add_column('settings', sa.Column('delete_reason', sa.String(length=255), nullable=True))
    op.add_column('tractors', sa.Column('delete_reason', sa.String(length=255), nullable=True))
    op.add_column('trip_expenses', sa.Column('delete_reason', sa.String(length=255), nullable=True))
    op.add_column('trip_status_histories', sa.Column('delete_reason', sa.String(length=255), nullable=True))
    op.add_column('trips', sa.Column('delete_reason', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('status', postgresql.ENUM('ACTIVE', 'INACTIVE', 'LOCKED', 'PENDING_VERIFICATION', name='user_status'), nullable=False, server_default='ACTIVE'))
    op.add_column('users', sa.Column('failed_login_attempts', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('users', sa.Column('locked_until', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('last_login_at', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('profile_picture_url', sa.String(length=500), nullable=True))
    op.add_column('users', sa.Column('token_version', sa.Integer(), nullable=False, server_default='1'))
    op.add_column('users', sa.Column('delete_reason', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'delete_reason')
    op.drop_column('users', 'token_version')
    op.drop_column('users', 'profile_picture_url')
    op.drop_column('users', 'last_login_at')
    op.drop_column('users', 'locked_until')
    op.drop_column('users', 'failed_login_attempts')
    op.drop_column('users', 'status')
    op.drop_column('trips', 'delete_reason')
    op.drop_column('trip_status_histories', 'delete_reason')
    op.drop_column('trip_expenses', 'delete_reason')
    op.drop_column('tractors', 'delete_reason')
    op.drop_column('settings', 'delete_reason')
    op.drop_column('roles', 'delete_reason')
    op.drop_column('quarries', 'delete_reason')
    op.add_column('permissions', sa.Column('code', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.drop_index('uq_permissions_name', table_name='permissions', postgresql_where='deleted_at IS NULL')
    op.drop_index(op.f('ix_permissions_name'), table_name='permissions')
    op.create_index(op.f('uq_permissions_code'), 'permissions', ['code'], unique=True, postgresql_where='(deleted_at IS NULL)')
    op.create_index(op.f('ix_permissions_code'), 'permissions', ['code'], unique=False)
    op.drop_column('permissions', 'delete_reason')
    op.drop_column('permissions', 'module')
    op.drop_column('permissions', 'name')
    op.drop_column('payments', 'delete_reason')
    op.drop_column('parties', 'delete_reason')
    op.drop_column('notifications', 'delete_reason')
    op.drop_column('materials', 'delete_reason')
    op.drop_column('maintenances', 'delete_reason')
    op.drop_column('maintenance_history', 'delete_reason')
    op.drop_column('invoices', 'delete_reason')
    op.drop_column('invoice_status_histories', 'delete_reason')
    op.drop_column('invoice_payments', 'delete_reason')
    op.drop_column('invoice_payment_history', 'delete_reason')
    op.drop_column('fuel_vendors', 'delete_reason')
    op.drop_column('fuel_transactions', 'delete_reason')
    op.drop_column('fuel_histories', 'delete_reason')
    op.drop_column('expenses', 'delete_reason')
    op.drop_column('expense_categories', 'delete_reason')
    op.drop_column('drivers', 'delete_reason')
    op.alter_column('audit_logs', 'action',
               existing_type=postgresql.ENUM('LOGIN', 'LOGOUT', 'CREATE', 'UPDATE', 'DELETE', 'RESTORE', 'PASSWORD_CHANGE', 'PERMISSION_CHANGE', name='audit_action'),
               type_=sa.VARCHAR(length=10),
               existing_nullable=False)
    op.drop_column('audit_logs', 'module')
    op.drop_index(op.f('ix_user_sessions_user_id'), table_name='user_sessions')
    op.drop_index(op.f('ix_user_sessions_refresh_token_jti'), table_name='user_sessions')
    op.drop_table('user_sessions')
    op.drop_table('user_preferences')
    op.drop_index(op.f('ix_password_history_user_id'), table_name='password_history')
    op.drop_table('password_history')
    op.drop_index(op.f('ix_login_history_user_id'), table_name='login_history')
    op.drop_table('login_history')
    
    # Drop ENUMs
    postgresql.ENUM(name='user_status').drop(op.get_bind(), checkfirst=True)
    postgresql.ENUM(name='session_status').drop(op.get_bind(), checkfirst=True)
    postgresql.ENUM(name='login_result').drop(op.get_bind(), checkfirst=True)
    postgresql.ENUM(name='audit_action').drop(op.get_bind(), checkfirst=True)
    postgresql.ENUM(name='permission_module').drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###

