"""Add ondelete SET NULL to current_trip_id

Revision ID: 4699d6e8bedc
Revises: bafbb857c0a4
Create Date: 2026-07-27 12:54:31.291831

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4699d6e8bedc'
down_revision: Union[str, Sequence[str], None] = 'bafbb857c0a4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_drivers_current_trip_id'), 'drivers', type_='foreignkey')
    op.create_foreign_key(None, 'drivers', 'trips', ['current_trip_id'], ['id'], ondelete='SET NULL')
    op.drop_constraint(op.f('fk_tractors_current_trip_id'), 'tractors', type_='foreignkey')
    op.create_foreign_key(None, 'tractors', 'trips', ['current_trip_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tractors', type_='foreignkey')
    op.create_foreign_key(op.f('fk_tractors_current_trip_id'), 'tractors', 'trips', ['current_trip_id'], ['id'])
    op.drop_constraint(None, 'drivers', type_='foreignkey')
    op.create_foreign_key(op.f('fk_drivers_current_trip_id'), 'drivers', 'trips', ['current_trip_id'], ['id'])
    # ### end Alembic commands ###
