"""create_trip_module

Revision ID: 82b5220e5f07
Revises: e4295163b548
Create Date: 2026-07-13 15:45:03.964334

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '82b5220e5f07'
down_revision: Union[str, Sequence[str], None] = 'e4295163b548'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    trip_status_enum = sa.Enum('PENDING', 'DISPATCHED', 'IN_PROGRESS', 'COMPLETED', 'CANCELLED', name='trip_status_enum')
    trip_status_enum.create(op.get_bind(), checkfirst=True)

    op.create_table('trip_status_histories',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('trip_id', sa.Uuid(), nullable=False),
    sa.Column('old_status', sa.String(length=20), nullable=True),
    sa.Column('new_status', sa.String(length=20), nullable=False),
    sa.Column('remarks', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('clock_timestamp()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('clock_timestamp()'), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('version_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['trip_id'], ['trips.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trip_status_histories_trip_id'), 'trip_status_histories', ['trip_id'], unique=False)
    op.add_column('drivers', sa.Column('current_trip_id', sa.Uuid(), nullable=True))
    op.create_index(op.f('ix_drivers_current_trip_id'), 'drivers', ['current_trip_id'], unique=False)
    op.create_foreign_key('drivers_current_trip_id_fkey', 'drivers', 'trips', ['current_trip_id'], ['id'], ondelete='SET NULL')
    op.add_column('tractors', sa.Column('current_trip_id', sa.Uuid(), nullable=True))
    op.create_index(op.f('ix_tractors_current_trip_id'), 'tractors', ['current_trip_id'], unique=False)
    op.create_foreign_key('tractors_current_trip_id_fkey', 'tractors', 'trips', ['current_trip_id'], ['id'], ondelete='SET NULL')
    op.add_column('trips', sa.Column('source_location', sa.String(length=100), nullable=False, server_default=""))
    op.add_column('trips', sa.Column('destination_location', sa.String(length=100), nullable=False, server_default=""))
    op.add_column('trips', sa.Column('expected_delivery_date', sa.Date(), nullable=False, server_default="2026-01-01"))
    op.add_column('trips', sa.Column('actual_delivery_date', sa.Date(), nullable=True))
    op.add_column('trips', sa.Column('freight_amount', sa.Numeric(precision=12, scale=2), nullable=False, server_default="0.00"))
    op.add_column('trips', sa.Column('advance_amount', sa.Numeric(precision=12, scale=2), nullable=False, server_default="0.00"))
    op.add_column('trips', sa.Column('status', sa.Enum('PENDING', 'DISPATCHED', 'IN_PROGRESS', 'COMPLETED', 'CANCELLED', name='trip_status_enum'), nullable=False, server_default="PENDING"))
    op.execute('DROP INDEX IF EXISTS ix_trips_material_id')
    op.execute('DROP INDEX IF EXISTS ix_trips_quarry_id')
    op.create_index(op.f('ix_trips_status'), 'trips', ['status'], unique=False)
    op.drop_constraint(op.f('trips_quarry_id_fkey'), 'trips', type_='foreignkey')
    op.drop_constraint(op.f('trips_material_id_fkey'), 'trips', type_='foreignkey')
    op.drop_column('trips', 'sale_amount')
    op.drop_column('trips', 'other_expense')
    op.drop_column('trips', 'cash_amount')
    op.drop_column('trips', 'transport_expense')
    op.drop_column('trips', 'purchase_amount')
    op.drop_column('trips', 'quarry_id')
    op.drop_column('trips', 'payment_type')
    op.drop_column('trips', 'quantity')
    op.drop_column('trips', 'purchase_rate')
    op.drop_column('trips', 'debit_amount')
    op.drop_column('trips', 'material_id')
    op.drop_column('trips', 'net_profit')
    op.drop_column('trips', 'sale_rate')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trips', sa.Column('sale_rate', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=False, server_default="0.00"))
    op.add_column('trips', sa.Column('net_profit', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=False, server_default="0.00"))
    op.add_column('trips', sa.Column('material_id', sa.UUID(), autoincrement=False, nullable=False, server_default="00000000-0000-0000-0000-000000000000"))
    op.add_column('trips', sa.Column('debit_amount', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=False, server_default="0.00"))
    op.add_column('trips', sa.Column('purchase_rate', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=False, server_default="0.00"))
    op.add_column('trips', sa.Column('quantity', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False, server_default="0.00"))
    op.add_column('trips', sa.Column('payment_type', sa.VARCHAR(length=20), autoincrement=False, nullable=False, server_default="CASH"))
    op.add_column('trips', sa.Column('quarry_id', sa.UUID(), autoincrement=False, nullable=False, server_default="00000000-0000-0000-0000-000000000000"))
    op.add_column('trips', sa.Column('purchase_amount', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=False, server_default="0.00"))
    op.add_column('trips', sa.Column('transport_expense', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=False, server_default="0.00"))
    op.add_column('trips', sa.Column('cash_amount', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=False, server_default="0.00"))
    op.add_column('trips', sa.Column('other_expense', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=False, server_default="0.00"))
    op.add_column('trips', sa.Column('sale_amount', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=False, server_default="0.00"))
    op.create_foreign_key(op.f('trips_material_id_fkey'), 'trips', 'materials', ['material_id'], ['id'], ondelete='RESTRICT')
    op.create_foreign_key(op.f('trips_quarry_id_fkey'), 'trips', 'quarries', ['quarry_id'], ['id'], ondelete='RESTRICT')
    op.drop_index(op.f('ix_trips_status'), table_name='trips')
    op.create_index(op.f('ix_trips_quarry_id'), 'trips', ['quarry_id'], unique=False)
    op.create_index(op.f('ix_trips_material_id'), 'trips', ['material_id'], unique=False)
    op.drop_column('trips', 'status')
    op.drop_column('trips', 'advance_amount')
    op.drop_column('trips', 'freight_amount')
    op.drop_column('trips', 'actual_delivery_date')
    op.drop_column('trips', 'expected_delivery_date')
    op.drop_column('trips', 'destination_location')
    op.drop_column('trips', 'source_location')
    op.drop_constraint('tractors_current_trip_id_fkey', 'tractors', type_='foreignkey')
    op.drop_index(op.f('ix_tractors_current_trip_id'), table_name='tractors')
    op.drop_column('tractors', 'current_trip_id')
    op.drop_constraint('drivers_current_trip_id_fkey', 'drivers', type_='foreignkey')
    op.drop_index(op.f('ix_drivers_current_trip_id'), table_name='drivers')
    op.drop_column('drivers', 'current_trip_id')
    op.drop_index(op.f('ix_trip_status_histories_trip_id'), table_name='trip_status_histories')
    op.drop_table('trip_status_histories')
    
    trip_status_enum = sa.Enum('PENDING', 'DISPATCHED', 'IN_PROGRESS', 'COMPLETED', 'CANCELLED', name='trip_status_enum')
    trip_status_enum.drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
