"""create_trip_expense_module

Revision ID: 8f496f09c3c6
Revises: 82b5220e5f07
Create Date: 2026-07-13 16:15:52.782940

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8f496f09c3c6'
down_revision: Union[str, Sequence[str], None] = '82b5220e5f07'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DROP TYPE IF EXISTS expense_type_enum CASCADE")
    op.execute("DROP TYPE IF EXISTS payment_mode_enum CASCADE")
    op.execute("DROP TYPE IF EXISTS payment_status_enum CASCADE")

    op.create_table('trip_expenses',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('expense_number', sa.String(length=50), nullable=False),
    sa.Column('trip_id', sa.Uuid(), nullable=False),
    sa.Column('party_id', sa.Uuid(), nullable=True),
    sa.Column('paid_to_name', sa.String(length=100), nullable=True),
    sa.Column('expense_type', sa.Enum('DIESEL', 'DRIVER_ADVANCE', 'DRIVER_BATA', 'FOOD', 'TOLL', 'LOADING', 'UNLOADING', 'REPAIR', 'MAINTENANCE', 'TYRE', 'PERMIT', 'RTO', 'POLICE_FINE', 'PARKING', 'BROKER_COMMISSION', 'OTHER', name='expense_type_enum'), nullable=False),
    sa.Column('expense_date', sa.Date(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('payment_mode', sa.Enum('CASH', 'UPI', 'BANK_TRANSFER', 'CARD', 'CHEQUE', 'CREDIT', 'OTHER', name='payment_mode_enum'), nullable=False),
    sa.Column('payment_status', sa.Enum('PAID', 'UNPAID', 'PARTIAL', name='payment_status_enum'), nullable=False),
    sa.Column('reference_number', sa.String(length=100), nullable=True),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('attachment_path', sa.String(length=500), nullable=True),
    sa.Column('attachment_name', sa.String(length=255), nullable=True),
    sa.Column('attachment_size', sa.Integer(), nullable=True),
    sa.Column('attachment_content_type', sa.String(length=100), nullable=True),
    sa.Column('created_ip', sa.String(length=45), nullable=True),
    sa.Column('updated_ip', sa.String(length=45), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('clock_timestamp()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('clock_timestamp()'), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('version_id', sa.Integer(), nullable=False),
    sa.CheckConstraint('amount > 0', name='chk_trip_expenses_amount'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['party_id'], ['parties.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['trip_id'], ['trips.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trip_expenses_expense_date'), 'trip_expenses', ['expense_date'], unique=False)
    op.create_index(op.f('ix_trip_expenses_expense_number'), 'trip_expenses', ['expense_number'], unique=False)
    op.create_index(op.f('ix_trip_expenses_expense_type'), 'trip_expenses', ['expense_type'], unique=False)
    op.create_index(op.f('ix_trip_expenses_party_id'), 'trip_expenses', ['party_id'], unique=False)
    op.create_index(op.f('ix_trip_expenses_trip_id'), 'trip_expenses', ['trip_id'], unique=False)
    op.create_index('uq_trip_expenses_number', 'trip_expenses', ['expense_number'], unique=True, postgresql_where='deleted_at IS NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_trip_expenses_number', table_name='trip_expenses', postgresql_where='deleted_at IS NULL')
    op.drop_index(op.f('ix_trip_expenses_trip_id'), table_name='trip_expenses')
    op.drop_index(op.f('ix_trip_expenses_party_id'), table_name='trip_expenses')
    op.drop_index(op.f('ix_trip_expenses_expense_type'), table_name='trip_expenses')
    op.drop_index(op.f('ix_trip_expenses_expense_number'), table_name='trip_expenses')
    op.drop_index(op.f('ix_trip_expenses_expense_date'), table_name='trip_expenses')
    op.drop_table('trip_expenses')
    
    expense_type_enum = sa.Enum('DIESEL', 'DRIVER_ADVANCE', 'DRIVER_BATA', 'FOOD', 'TOLL', 'LOADING', 'UNLOADING', 'REPAIR', 'MAINTENANCE', 'TYRE', 'PERMIT', 'RTO', 'POLICE_FINE', 'PARKING', 'BROKER_COMMISSION', 'OTHER', name='expense_type_enum')
    expense_type_enum.drop(op.get_bind(), checkfirst=True)

    payment_mode_enum = sa.Enum('CASH', 'UPI', 'BANK_TRANSFER', 'CARD', 'CHEQUE', 'CREDIT', 'OTHER', name='payment_mode_enum')
    payment_mode_enum.drop(op.get_bind(), checkfirst=True)

    payment_status_enum = sa.Enum('PAID', 'UNPAID', 'PARTIAL', name='payment_status_enum')
    payment_status_enum.drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
