"""create_invoice_payment_module

Revision ID: afa9143ad701
Revises: 6a4180bd4769
Create Date: 2026-07-13 17:22:49.293748

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects.postgresql import ENUM as PGEnum


# revision identifiers, used by Alembic.
revision: str = 'afa9143ad701'
down_revision: Union[str, Sequence[str], None] = '6a4180bd4769'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Ensure PaymentStatus enum values exist (PostgreSQL requires ALTER TYPE for new values)
    op.execute("ALTER TYPE payment_status_enum ADD VALUE IF NOT EXISTS 'SUCCESS'")
    op.execute("ALTER TYPE payment_status_enum ADD VALUE IF NOT EXISTS 'PENDING'")
    op.execute("ALTER TYPE payment_status_enum ADD VALUE IF NOT EXISTS 'FAILED'")
    op.execute("ALTER TYPE payment_status_enum ADD VALUE IF NOT EXISTS 'CANCELLED'")
    
    # Drop payment_source_enum if it existed from failed attempts
    op.execute("DROP TYPE IF EXISTS payment_source_enum CASCADE")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('invoice_payments',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('receipt_number', sa.String(length=30), nullable=False),
    sa.Column('invoice_id', sa.Uuid(), nullable=False),
    sa.Column('payment_date', sa.Date(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('payment_source', sa.Enum('CASH', 'BANK', 'UPI', 'CHEQUE', 'CARD', 'ONLINE', 'OTHER', name='payment_source_enum'), nullable=False),
    sa.Column('payment_status', PGEnum('PAID', 'UNPAID', 'PARTIAL', 'SUCCESS', 'PENDING', 'FAILED', 'CANCELLED', name='payment_status_enum', create_type=False), nullable=False),
    sa.Column('bank_name', sa.String(length=100), nullable=True),
    sa.Column('account_holder', sa.String(length=100), nullable=True),
    sa.Column('transaction_number', sa.String(length=100), nullable=True),
    sa.Column('cheque_number', sa.String(length=50), nullable=True),
    sa.Column('cheque_date', sa.Date(), nullable=True),
    sa.Column('reference_number', sa.String(length=100), nullable=True),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('attachment', sa.String(length=255), nullable=True),
    sa.Column('received_by', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('clock_timestamp()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('clock_timestamp()'), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('version_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], ),
    sa.ForeignKeyConstraint(['received_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_invoice_payments_created_at', 'invoice_payments', ['created_at'], unique=False)
    op.create_index('ix_invoice_payments_invoice_id', 'invoice_payments', ['invoice_id'], unique=False)
    op.create_index('ix_invoice_payments_payment_date', 'invoice_payments', ['payment_date'], unique=False)
    op.create_index('ix_invoice_payments_payment_source', 'invoice_payments', ['payment_source'], unique=False)
    op.create_index('ix_invoice_payments_payment_status', 'invoice_payments', ['payment_status'], unique=False)
    op.create_index('ix_invoice_payments_receipt_number', 'invoice_payments', ['receipt_number'], unique=True, postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_table('invoice_payment_history',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('payment_id', sa.Uuid(), nullable=False),
    sa.Column('old_amount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('new_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('old_status', sa.String(length=50), nullable=True),
    sa.Column('new_status', sa.String(length=50), nullable=False),
    sa.Column('old_payment_source', sa.String(length=50), nullable=True),
    sa.Column('new_payment_source', sa.String(length=50), nullable=False),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('changed_by', sa.Uuid(), nullable=True),
    sa.Column('changed_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('clock_timestamp()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('clock_timestamp()'), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('version_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['changed_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['payment_id'], ['invoice_payments.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('invoice_payment_history')
    op.drop_index('ix_invoice_payments_receipt_number', table_name='invoice_payments', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_index('ix_invoice_payments_payment_status', table_name='invoice_payments')
    op.drop_index('ix_invoice_payments_payment_source', table_name='invoice_payments')
    op.drop_index('ix_invoice_payments_payment_date', table_name='invoice_payments')
    op.drop_index('ix_invoice_payments_invoice_id', table_name='invoice_payments')
    op.drop_index('ix_invoice_payments_created_at', table_name='invoice_payments')
    op.drop_table('invoice_payments')
    # ### end Alembic commands ###
    op.execute("DROP TYPE IF EXISTS payment_source_enum CASCADE")
