"""alter_tractor_table_schema

Revision ID: b67bcabd59a8
Revises: 630fcd950c9a
Create Date: 2026-07-13 15:00:32.646897

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b67bcabd59a8'
down_revision: Union[str, Sequence[str], None] = '630fcd950c9a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tractors', sa.Column('tractor_number', sa.String(length=30), nullable=False, server_default=""))
    op.add_column('tractors', sa.Column('owner_name', sa.String(length=100), nullable=False, server_default=""))
    op.add_column('tractors', sa.Column('rc_number', sa.String(length=50), nullable=False, server_default=""))
    op.add_column('tractors', sa.Column('insurance_number', sa.String(length=100), nullable=True))
    op.add_column('tractors', sa.Column('manufacturer', sa.String(length=50), nullable=True))
    op.add_column('tractors', sa.Column('registration_date', sa.Date(), nullable=True))
    op.add_column('tractors', sa.Column('remarks', sa.String(length=500), nullable=True))
    op.alter_column('tractors', 'model',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.drop_index(op.f('ix_tractors_registration_number'), table_name='tractors')
    op.drop_index(op.f('uq_tractors_registration_number'), table_name='tractors', postgresql_where='(deleted_at IS NULL)')
    op.create_index(op.f('ix_tractors_rc_number'), 'tractors', ['rc_number'], unique=False)
    op.create_index(op.f('ix_tractors_tractor_number'), 'tractors', ['tractor_number'], unique=False)
    op.create_index('uq_tractors_rc_number', 'tractors', ['rc_number'], unique=True, postgresql_where='deleted_at IS NULL')
    op.create_index('uq_tractors_tractor_number', 'tractors', ['tractor_number'], unique=True, postgresql_where='deleted_at IS NULL')
    op.drop_column('tractors', 'current_odometer')
    op.drop_column('tractors', 'make')
    op.drop_column('tractors', 'road_tax_expiry')
    op.drop_column('tractors', 'fitness_certificate_expiry')
    op.drop_column('tractors', 'registration_number')
    op.drop_column('tractors', 'chassis_number')
    op.drop_column('tractors', 'year_manufactured')
    op.drop_column('tractors', 'engine_number')
    op.drop_column('tractors', 'status')
    op.drop_column('tractors', 'ownership_type')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tractors', sa.Column('ownership_type', sa.VARCHAR(length=20), autoincrement=False, nullable=False, server_default="OWNED"))
    op.add_column('tractors', sa.Column('status', postgresql.ENUM('active', 'in_maintenance', 'out_of_service', name='tractor_status_enum'), autoincrement=False, nullable=False, server_default="active"))
    op.add_column('tractors', sa.Column('engine_number', sa.VARCHAR(length=100), autoincrement=False, nullable=False, server_default=""))
    op.add_column('tractors', sa.Column('year_manufactured', sa.INTEGER(), autoincrement=False, nullable=False, server_default="2020"))
    op.add_column('tractors', sa.Column('chassis_number', sa.VARCHAR(length=100), autoincrement=False, nullable=False, server_default=""))
    op.add_column('tractors', sa.Column('registration_number', sa.VARCHAR(length=30), autoincrement=False, nullable=False, server_default=""))
    op.add_column('tractors', sa.Column('fitness_certificate_expiry', sa.DATE(), autoincrement=False, nullable=False, server_default="2026-07-10"))
    op.add_column('tractors', sa.Column('road_tax_expiry', sa.DATE(), autoincrement=False, nullable=False, server_default="2026-07-10"))
    op.add_column('tractors', sa.Column('make', sa.VARCHAR(length=50), autoincrement=False, nullable=False, server_default=""))
    op.add_column('tractors', sa.Column('current_odometer', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False, server_default="0.00"))
    op.drop_index('uq_tractors_tractor_number', table_name='tractors', postgresql_where='deleted_at IS NULL')
    op.drop_index('uq_tractors_rc_number', table_name='tractors', postgresql_where='deleted_at IS NULL')
    op.drop_index(op.f('ix_tractors_tractor_number'), table_name='tractors')
    op.drop_index(op.f('ix_tractors_rc_number'), table_name='tractors')
    op.create_index(op.f('uq_tractors_registration_number'), 'tractors', ['registration_number'], unique=True, postgresql_where='(deleted_at IS NULL)')
    op.create_index(op.f('ix_tractors_registration_number'), 'tractors', ['registration_number'], unique=False)
    op.alter_column('tractors', 'model',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.drop_column('tractors', 'remarks')
    op.drop_column('tractors', 'registration_date')
    op.drop_column('tractors', 'manufacturer')
    op.drop_column('tractors', 'insurance_number')
    op.drop_column('tractors', 'rc_number')
    op.drop_column('tractors', 'owner_name')
    op.drop_column('tractors', 'tractor_number')
    # ### end Alembic commands ###
