"""initial_schema

Revision ID: bafbb857c0a4
Revises: 
Create Date: 2026-07-21 15:44:05.354038

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'bafbb857c0a4'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('phone', sa.String(length=30), nullable=True),
    sa.Column('status', postgresql.ENUM('ACTIVE', 'INACTIVE', 'LOCKED', 'PENDING_VERIFICATION', name='user_status'), nullable=False),
    sa.Column('failed_login_attempts', sa.Integer(), nullable=False),
    sa.Column('locked_until', sa.DateTime(), nullable=True),
    sa.Column('last_login_at', sa.DateTime(), nullable=True),
    sa.Column('profile_picture_url', sa.String(length=500), nullable=True),
    sa.Column('token_version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('clock_timestamp()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('clock_timestamp()'), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('delete_reason', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('version_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=False)
    op.create_index('uq_users_email', 'users', ['email'], unique=True, postgresql_where='deleted_at IS NULL')
    op.create_index('uq_users_username', 'users', ['username'], unique=True, postgresql_where='deleted_at IS NULL')
    op.create_table('roles',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('display_name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('clock_timestamp()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('clock_timestamp()'), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('delete_reason', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('version_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_roles_name'), 'roles', ['name'], unique=False)
    op.create_index('uq_roles_name', 'roles', ['name'], unique=True, postgresql_where='deleted_at IS NULL')
    op.create_table('permissions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('module', postgresql.ENUM('AUTH', 'USERS', 'ROLES', 'DRIVERS', 'TRACTORS', 'TRIPS', 'INVOICES', 'MAINTENANCE', 'FUEL', 'REPORTS', 'SETTINGS', name='permission_module'), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('clock_timestamp()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('clock_timestamp()'), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('delete_reason', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('version_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_permissions_name'), 'permissions', ['name'], unique=False)
    op.create_index('uq_permissions_name', 'permissions', ['name'], unique=True, postgresql_where='deleted_at IS NULL')
    op.create_table('role_permissions',
    sa.Column('role_id', sa.Uuid(), nullable=False),
    sa.Column('permission_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('clock_timestamp()'), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['permission_id'], ['permissions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('role_id', 'permission_id')
    )
    op.create_table('user_roles',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('role_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('clock_timestamp()'), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'role_id')
    )
    op.create_table('user_permissions',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('permission_id', sa.Uuid(), nullable=False),
    sa.Column('is_granted', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('clock_timestamp()'), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['permission_id'], ['permissions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'permission_id')
    )
    op.create_table('parties',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('party_type', sa.String(length=20), nullable=False),
    sa.Column('mobile_number', sa.String(length=30), nullable=False),
    sa.Column('alternate_mobile', sa.String(length=30), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('gst_number', sa.String(length=15), nullable=True),
    sa.Column('pan_number', sa.String(length=10), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('state', sa.String(length=100), nullable=True),
    sa.Column('pincode', sa.String(length=20), nullable=True),
    sa.Column('contact_person', sa.String(length=100), nullable=True),
    sa.Column('opening_balance', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('credit_limit', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('remarks', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('clock_timestamp()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('clock_timestamp()'), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('delete_reason', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('version_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_parties_city'), 'parties', ['city'], unique=False)
    op.create_index(op.f('ix_parties_contact_person'), 'parties', ['contact_person'], unique=False)
    op.create_index(op.f('ix_parties_gst_number'), 'parties', ['gst_number'], unique=False)
    op.create_index(op.f('ix_parties_mobile_number'), 'parties', ['mobile_number'], unique=False)
    op.create_index(op.f('ix_parties_name'), 'parties', ['name'], unique=False)
    op.create_index(op.f('ix_parties_pan_number'), 'parties', ['pan_number'], unique=False)
    op.create_index(op.f('ix_parties_party_type'), 'parties', ['party_type'], unique=False)
    op.create_index(op.f('ix_parties_state'), 'parties', ['state'], unique=False)
    op.create_index('uq_parties_gst_number', 'parties', ['gst_number'], unique=True, postgresql_where='gst_number IS NOT NULL AND deleted_at IS NULL')
    op.create_index('uq_parties_mobile_number', 'parties', ['mobile_number'], unique=True, postgresql_where='deleted_at IS NULL')
    op.create_index('uq_parties_pan_number', 'parties', ['pan_number'], unique=True, postgresql_where='pan_number IS NOT NULL AND deleted_at IS NULL')
    op.create_table('tractors',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tractor_number', sa.String(length=30), nullable=False),
    sa.Column('owner_name', sa.String(length=100), nullable=False),
    sa.Column('rc_number', sa.String(length=50), nullable=False),
    sa.Column('insurance_number', sa.String(length=100), nullable=True),
    sa.Column('insurance_expiry', sa.Date(), nullable=False),
    sa.Column('manufacturer', sa.String(length=50), nullable=True),
    sa.Column('model', sa.String(length=50), nullable=True),
    sa.Column('registration_date', sa.Date(), nullable=True),
    sa.Column('remarks', sa.String(length=500), nullable=True),
    sa.Column('current_trip_id', sa.Uuid(), nullable=True),
    sa.Column('status', postgresql.ENUM('ACTIVE', 'IN_MAINTENANCE', 'OUT_OF_SERVICE', name='tractor_status_enum'), nullable=False),
    sa.Column('current_odometer', sa.Integer(), nullable=False),
    sa.Column('fuel_capacity', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('clock_timestamp()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('clock_timestamp()'), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('delete_reason', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('version_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tractors_current_trip_id'), 'tractors', ['current_trip_id'], unique=False)
    op.create_index(op.f('ix_tractors_rc_number'), 'tractors', ['rc_number'], unique=False)
    op.create_index(op.f('ix_tractors_tractor_number'), 'tractors', ['tractor_number'], unique=False)
    op.create_index('uq_tractors_rc_number', 'tractors', ['rc_number'], unique=True, postgresql_where='deleted_at IS NULL')
    op.create_index('uq_tractors_tractor_number', 'tractors', ['tractor_number'], unique=True, postgresql_where='deleted_at IS NULL')
    op.create_table('drivers',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('address', sa.String(length=500), nullable=True),
    sa.Column('employee_code', sa.String(length=50), nullable=False),
    sa.Column('license_number', sa.String(length=50), nullable=False),
    sa.Column('license_expiry', sa.Date(), nullable=False),
    sa.Column('license_class', sa.String(length=30), nullable=False),
    sa.Column('contact_phone', sa.String(length=30), nullable=False),
    sa.Column('emergency_contact_phone', sa.String(length=30), nullable=True),
    sa.Column('fixed_salary', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('commission_percentage', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('driver_type', sa.String(length=20), nullable=False),
    sa.Column('current_status', sa.Enum('available', 'on_trip', 'on_leave', 'inactive', name='driver_status_enum'), nullable=False),
    sa.Column('current_trip_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('clock_timestamp()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('clock_timestamp()'), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('delete_reason', sa.String(length=255), nullable=True),
    sa.Column('version_id', sa.Integer(), nullable=False),
    sa.CheckConstraint('commission_percentage >= 0 AND commission_percentage <= 100', name='chk_drivers_commission'),
    sa.CheckConstraint('fixed_salary >= 0', name='chk_drivers_salary'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_drivers_current_trip_id'), 'drivers', ['current_trip_id'], unique=False)
    op.create_index(op.f('ix_drivers_employee_code'), 'drivers', ['employee_code'], unique=False)
    op.create_index(op.f('ix_drivers_license_number'), 'drivers', ['license_number'], unique=False)
    op.create_index(op.f('ix_drivers_user_id'), 'drivers', ['user_id'], unique=False)
    op.create_index('uq_drivers_contact_phone', 'drivers', ['contact_phone'], unique=True, postgresql_where='deleted_at IS NULL')
    op.create_index('uq_drivers_employee_code', 'drivers', ['employee_code'], unique=True, postgresql_where='deleted_at IS NULL')
    op.create_index('uq_drivers_license_number', 'drivers', ['license_number'], unique=True, postgresql_where='deleted_at IS NULL')
    op.create_table('trips',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('trip_number', sa.String(length=50), nullable=False),
    sa.Column('trip_date', sa.Date(), nullable=False),
    sa.Column('tractor_id', sa.Uuid(), nullable=False),
    sa.Column('driver_id', sa.Uuid(), nullable=False),
    sa.Column('party_id', sa.Uuid(), nullable=False),
    sa.Column('source_location', sa.String(length=100), nullable=False),
    sa.Column('destination_location', sa.String(length=100), nullable=False),
    sa.Column('expected_delivery_date', sa.Date(), nullable=False),
    sa.Column('actual_delivery_date', sa.Date(), nullable=True),
    sa.Column('freight_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('advance_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'DISPATCHED', 'IN_PROGRESS', 'COMPLETED', 'CANCELLED', name='trip_status_enum'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('clock_timestamp()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('clock_timestamp()'), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('delete_reason', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('version_id', sa.Integer(), nullable=False),
    sa.CheckConstraint('advance_amount <= freight_amount', name='chk_trips_advance_freight'),
    sa.CheckConstraint('advance_amount >= 0', name='chk_trips_advance_amount'),
    sa.CheckConstraint('freight_amount > 0', name='chk_trips_freight_amount'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['driver_id'], ['drivers.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['party_id'], ['parties.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['tractor_id'], ['tractors.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trips_driver_id'), 'trips', ['driver_id'], unique=False)
    op.create_index(op.f('ix_trips_party_id'), 'trips', ['party_id'], unique=False)
    op.create_index(op.f('ix_trips_status'), 'trips', ['status'], unique=False)
    op.create_index(op.f('ix_trips_tractor_id'), 'trips', ['tractor_id'], unique=False)
    op.create_index(op.f('ix_trips_trip_number'), 'trips', ['trip_number'], unique=False)
    op.create_index('uq_trips_trip_number', 'trips', ['trip_number'], unique=True, postgresql_where='deleted_at IS NULL')
    op.create_table('audit_logs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('action', postgresql.ENUM('LOGIN', 'LOGOUT', 'CREATE', 'UPDATE', 'DELETE', 'RESTORE', 'PASSWORD_CHANGE', 'PERMISSION_CHANGE', name='audit_action'), nullable=False),
    sa.Column('module', postgresql.ENUM('AUTH', 'USERS', 'ROLES', 'DRIVERS', 'TRACTORS', 'TRIPS', 'INVOICES', 'MAINTENANCE', 'FUEL', 'REPORTS', 'SETTINGS', name='permission_module'), nullable=False),
    sa.Column('table_name', sa.String(length=100), nullable=False),
    sa.Column('record_id', sa.Uuid(), nullable=False),
    sa.Column('old_values', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('new_values', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.String(length=512), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('clock_timestamp()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_audit_logs_created_at', 'audit_logs', [sa.literal_column('created_at DESC')], unique=False)
    op.create_index('idx_audit_logs_target_record', 'audit_logs', ['table_name', 'record_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_record_id'), 'audit_logs', ['record_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_table_name'), 'audit_logs', ['table_name'], unique=False)
    op.create_index(op.f('ix_audit_logs_user_id'), 'audit_logs', ['user_id'], unique=False)
    op.create_table('expense_categories',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('clock_timestamp()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('clock_timestamp()'), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('delete_reason', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('version_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_expense_categories_name'), 'expense_categories', ['name'], unique=False)
    op.create_index('uq_expense_categories_name', 'expense_categories', ['name'], unique=True, postgresql_where='deleted_at IS NULL')
    op.create_table('fuel_vendors',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('vendor_code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('contact_person', sa.String(length=255), nullable=True),
    sa.Column('mobile', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('gst_number', sa.String(length=50), nullable=True),
    sa.Column('address', sa.String(length=500), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('state', sa.String(length=100), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('opening_time', sa.Time(), nullable=True),
    sa.Column('closing_time', sa.Time(), nullable=True),
    sa.Column('is_company_owned', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.String(length=1000), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('clock_timestamp()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('clock_timestamp()'), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('delete_reason', sa.String(length=255), nullable=True),
    sa.Column('version_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fuel_vendors_name'), 'fuel_vendors', ['name'], unique=False)
    op.create_index(op.f('ix_fuel_vendors_vendor_code'), 'fuel_vendors', ['vendor_code'], unique=True)
    op.create_table('login_history',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.String(length=512), nullable=True),
    sa.Column('device_fingerprint', sa.String(length=255), nullable=True),
    sa.Column('browser', sa.String(length=100), nullable=True),
    sa.Column('os', sa.String(length=100), nullable=True),
    sa.Column('platform', sa.String(length=100), nullable=True),
    sa.Column('result', postgresql.ENUM('SUCCESS', 'FAILED_BAD_CREDENTIALS', 'FAILED_LOCKED', 'FAILED_INACTIVE', name='login_result'), nullable=False),
    sa.Column('failure_reason', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('clock_timestamp()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('clock_timestamp()'), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('delete_reason', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('version_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_login_history_user_id'), 'login_history', ['user_id'], unique=False)
    op.create_table('maintenances',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('maintenance_number', sa.String(length=50), nullable=False),
    sa.Column('tractor_id', sa.Uuid(), nullable=False),
    sa.Column('maintenance_type', postgresql.ENUM('ENGINE_SERVICE', 'GENERAL_SERVICE', 'BREAKDOWN', 'REPAIR', 'TYRE_CHANGE', 'BATTERY', 'INSURANCE', 'FITNESS', 'PERMIT', 'PUC', 'ENGINE_OVERHAUL', 'OIL_CHANGE', 'FILTER_CHANGE', 'BRAKE_SERVICE', 'CLUTCH', 'SUSPENSION', 'ELECTRICAL', 'BODY_WORK', 'OTHER', name='maintenance_type_enum'), nullable=False),
    sa.Column('priority', postgresql.ENUM('LOW', 'MEDIUM', 'HIGH', 'URGENT', name='maintenance_priority_enum'), nullable=False),
    sa.Column('status', postgresql.ENUM('SCHEDULED', 'IN_PROGRESS', 'COMPLETED', 'CANCELLED', name='maintenance_status_enum'), nullable=False),
    sa.Column('vendor_name', sa.String(length=100), nullable=True),
    sa.Column('vendor_mobile', sa.String(length=15), nullable=True),
    sa.Column('service_center', sa.String(length=150), nullable=True),
    sa.Column('invoice_number', sa.String(length=100), nullable=True),
    sa.Column('scheduled_date', sa.Date(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('completion_date', sa.Date(), nullable=True),
    sa.Column('next_service_date', sa.Date(), nullable=True),
    sa.Column('current_odometer', sa.Integer(), nullable=False),
    sa.Column('next_service_odometer', sa.Integer(), nullable=True),
    sa.Column('parts_cost', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('labor_cost', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('other_cost', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('total_cost', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('remarks', sa.String(length=500), nullable=True),
    sa.Column('attachment', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('clock_timestamp()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('clock_timestamp()'), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('delete_reason', sa.String(length=255), nullable=True),
    sa.Column('version_id', sa.Integer(), nullable=False),
    sa.CheckConstraint('labor_cost >= 0', name='chk_maintenance_labor_cost'),
    sa.CheckConstraint('other_cost >= 0', name='chk_maintenance_other_cost'),
    sa.CheckConstraint('parts_cost >= 0', name='chk_maintenance_parts_cost'),
    sa.CheckConstraint('total_cost >= 0', name='chk_maintenance_total_cost'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tractor_id'], ['tractors.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_maintenance_created_at', 'maintenances', ['created_at'], unique=False)
    op.create_index('idx_maintenance_number', 'maintenances', ['maintenance_number'], unique=False)
    op.create_index('idx_maintenance_scheduled_date', 'maintenances', ['scheduled_date'], unique=False)
    op.create_index('idx_maintenance_status', 'maintenances', ['status'], unique=False)
    op.create_index('idx_maintenance_tractor_id', 'maintenances', ['tractor_id'], unique=False)
    op.create_index('idx_maintenance_type', 'maintenances', ['maintenance_type'], unique=False)
    op.create_index('idx_unique_maintenance_number', 'maintenances', ['maintenance_number'], unique=True, postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_table('materials',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('unit_of_measure', sa.String(length=20), nullable=False),
    sa.Column('density_factor', sa.Numeric(precision=6, scale=3), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('clock_timestamp()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('clock_timestamp()'), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('delete_reason', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('version_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_materials_name'), 'materials', ['name'], unique=False)
    op.create_index('uq_materials_name', 'materials', ['name'], unique=True, postgresql_where='deleted_at IS NULL')
    op.create_table('notifications',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('type', sa.Enum('ALERT', 'SYSTEM', 'INFO', 'EXPIRY_REMINDER', 'PAYMENT_REMINDER', name='notification_type_enum'), nullable=False),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('clock_timestamp()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('clock_timestamp()'), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('delete_reason', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('version_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_notifications_unread', 'notifications', ['user_id', 'read_at'], unique=False, postgresql_where='read_at IS NULL')
    op.create_index(op.f('ix_notifications_user_id'), 'notifications', ['user_id'], unique=False)
    op.create_table('password_history',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('clock_timestamp()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('clock_timestamp()'), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('delete_reason', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('version_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_password_history_user_id'), 'password_history', ['user_id'], unique=False)
    op.create_table('quarries',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('location', sa.Text(), nullable=False),
    sa.Column('contact_phone', sa.String(length=30), nullable=True),
    sa.Column('permit_number', sa.String(length=100), nullable=True),
    sa.Column('is_third_party', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('clock_timestamp()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('clock_timestamp()'), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('delete_reason', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('version_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_quarries_name'), 'quarries', ['name'], unique=False)
    op.create_index('uq_quarries_name', 'quarries', ['name'], unique=True, postgresql_where='deleted_at IS NULL')
    op.create_table('refresh_tokens',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('token', sa.String(length=512), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('issued_at', sa.DateTime(timezone=True), server_default=sa.text('clock_timestamp()'), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('replaced_by_token', sa.String(length=512), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_refresh_tokens_token'), 'refresh_tokens', ['token'], unique=True)
    op.create_table('settings',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('clock_timestamp()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('clock_timestamp()'), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('delete_reason', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('version_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_settings_key'), 'settings', ['key'], unique=False)
    op.create_index('uq_settings_key', 'settings', ['key'], unique=True, postgresql_where='deleted_at IS NULL')
    op.create_table('trip_status_histories',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('trip_id', sa.Uuid(), nullable=False),
    sa.Column('old_status', sa.String(length=20), nullable=True),
    sa.Column('new_status', sa.String(length=20), nullable=False),
    sa.Column('remarks', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('clock_timestamp()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('clock_timestamp()'), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('delete_reason', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('version_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['trip_id'], ['trips.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trip_status_histories_trip_id'), 'trip_status_histories', ['trip_id'], unique=False)
    op.create_table('user_preferences',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('theme', sa.String(length=50), nullable=False),
    sa.Column('language', sa.String(length=10), nullable=False),
    sa.Column('timezone', sa.String(length=50), nullable=False),
    sa.Column('date_format', sa.String(length=20), nullable=False),
    sa.Column('number_format', sa.String(length=20), nullable=False),
    sa.Column('dashboard_layout', sa.String(length=255), nullable=False),
    sa.Column('notification_settings', sa.String(length=1000), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('clock_timestamp()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('clock_timestamp()'), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('delete_reason', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('version_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('user_sessions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('device_fingerprint', sa.String(length=255), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.String(length=512), nullable=True),
    sa.Column('refresh_token_jti', sa.String(length=255), nullable=True),
    sa.Column('status', postgresql.ENUM('ACTIVE', 'REVOKED', 'EXPIRED', name='session_status'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('clock_timestamp()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('clock_timestamp()'), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('delete_reason', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('version_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_sessions_refresh_token_jti'), 'user_sessions', ['refresh_token_jti'], unique=False)
    op.create_index(op.f('ix_user_sessions_user_id'), 'user_sessions', ['user_id'], unique=False)
    op.create_table('expenses',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('category_id', sa.Uuid(), nullable=False),
    sa.Column('tractor_id', sa.Uuid(), nullable=True),
    sa.Column('trip_id', sa.Uuid(), nullable=True),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('expense_date', sa.Date(), nullable=False),
    sa.Column('recipient', sa.String(length=150), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('receipt_url', sa.String(length=512), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('clock_timestamp()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('clock_timestamp()'), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('delete_reason', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('version_id', sa.Integer(), nullable=False),
    sa.CheckConstraint('amount > 0', name='chk_expenses_amount'),
    sa.ForeignKeyConstraint(['category_id'], ['expense_categories.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tractor_id'], ['tractors.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['trip_id'], ['trips.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_expenses_date', 'expenses', [sa.literal_column('expense_date DESC')], unique=False)
    op.create_index(op.f('ix_expenses_category_id'), 'expenses', ['category_id'], unique=False)
    op.create_index(op.f('ix_expenses_tractor_id'), 'expenses', ['tractor_id'], unique=False)
    op.create_index(op.f('ix_expenses_trip_id'), 'expenses', ['trip_id'], unique=False)
    op.create_table('fuel_transactions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('fuel_number', sa.String(length=50), nullable=False),
    sa.Column('tractor_id', sa.UUID(), nullable=False),
    sa.Column('trip_id', sa.UUID(), nullable=True),
    sa.Column('driver_id', sa.UUID(), nullable=False),
    sa.Column('vendor_id', sa.UUID(), nullable=False),
    sa.Column('station_type', sa.Enum('COMPANY', 'PRIVATE', 'MOBILE', 'OTHER', name='fuel_station_type_enum'), nullable=False),
    sa.Column('fuel_type', sa.Enum('DIESEL', 'PETROL', 'CNG', 'LNG', 'ELECTRIC', 'OTHER', name='fuel_type_enum'), nullable=False),
    sa.Column('fuel_date', sa.Date(), nullable=False),
    sa.Column('odometer', sa.Integer(), nullable=False),
    sa.Column('liters', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('rate_per_liter', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('previous_odometer', sa.Integer(), nullable=True),
    sa.Column('distance_since_last_fill', sa.Integer(), nullable=True),
    sa.Column('average_kmpl', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('payment_mode', sa.Enum('CASH', 'CARD', 'UPI', 'BANK_TRANSFER', 'FUEL_CARD', 'CREDIT', 'OTHER', name='fuel_payment_mode_enum'), nullable=False),
    sa.Column('invoice_number', sa.String(length=100), nullable=True),
    sa.Column('remarks', sa.String(length=1000), nullable=True),
    sa.Column('attachment', sa.String(length=500), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('is_full_tank', sa.Boolean(), nullable=False),
    sa.Column('fuel_card_number', sa.String(length=100), nullable=True),
    sa.Column('authorization_code', sa.String(length=100), nullable=True),
    sa.Column('transaction_reference', sa.String(length=255), nullable=True),
    sa.Column('is_suspicious', sa.Boolean(), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'VERIFIED', 'APPROVED', 'CANCELLED', name='fuel_transaction_status_enum'), nullable=False),
    sa.Column('gps_latitude', sa.Float(), nullable=True),
    sa.Column('gps_longitude', sa.Float(), nullable=True),
    sa.Column('gps_accuracy', sa.Float(), nullable=True),
    sa.Column('device_id', sa.String(length=100), nullable=True),
    sa.Column('location_address', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('clock_timestamp()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('clock_timestamp()'), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('delete_reason', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('version_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['driver_id'], ['drivers.id'], ),
    sa.ForeignKeyConstraint(['tractor_id'], ['tractors.id'], ),
    sa.ForeignKeyConstraint(['trip_id'], ['trips.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['vendor_id'], ['fuel_vendors.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fuel_transactions_driver_id'), 'fuel_transactions', ['driver_id'], unique=False)
    op.create_index(op.f('ix_fuel_transactions_fuel_date'), 'fuel_transactions', ['fuel_date'], unique=False)
    op.create_index(op.f('ix_fuel_transactions_fuel_number'), 'fuel_transactions', ['fuel_number'], unique=True)
    op.create_index(op.f('ix_fuel_transactions_invoice_number'), 'fuel_transactions', ['invoice_number'], unique=False)
    op.create_index(op.f('ix_fuel_transactions_tractor_id'), 'fuel_transactions', ['tractor_id'], unique=False)
    op.create_index(op.f('ix_fuel_transactions_trip_id'), 'fuel_transactions', ['trip_id'], unique=False)
    op.create_index(op.f('ix_fuel_transactions_vendor_id'), 'fuel_transactions', ['vendor_id'], unique=False)
    op.create_table('invoices',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('invoice_number', sa.String(length=50), nullable=False),
    sa.Column('trip_id', sa.Uuid(), nullable=False),
    sa.Column('party_id', sa.Uuid(), nullable=False),
    sa.Column('invoice_date', sa.Date(), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=False),
    sa.Column('gross_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('received_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('balance_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('DRAFT', 'ISSUED', 'PARTIALLY_PAID', 'PAID', 'CANCELLED', name='invoice_status_enum'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('clock_timestamp()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('clock_timestamp()'), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('delete_reason', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('version_id', sa.Integer(), nullable=False),
    sa.CheckConstraint('balance_amount = gross_amount - received_amount', name='chk_invoices_balance_amount'),
    sa.CheckConstraint('gross_amount >= 0', name='chk_invoices_gross_amount'),
    sa.CheckConstraint('received_amount >= 0', name='chk_invoices_received_amount'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['party_id'], ['parties.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['trip_id'], ['trips.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_invoices_invoice_date'), 'invoices', ['invoice_date'], unique=False)
    op.create_index(op.f('ix_invoices_invoice_number'), 'invoices', ['invoice_number'], unique=False)
    op.create_index(op.f('ix_invoices_party_id'), 'invoices', ['party_id'], unique=False)
    op.create_index(op.f('ix_invoices_status'), 'invoices', ['status'], unique=False)
    op.create_index(op.f('ix_invoices_trip_id'), 'invoices', ['trip_id'], unique=False)
    op.create_index('uq_invoices_invoice_number', 'invoices', ['invoice_number'], unique=True, postgresql_where='deleted_at IS NULL')
    op.create_index('uq_invoices_trip_id', 'invoices', ['trip_id'], unique=True, postgresql_where='deleted_at IS NULL')
    op.create_table('maintenance_history',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('maintenance_id', sa.Uuid(), nullable=False),
    sa.Column('old_status', sa.String(length=50), nullable=True),
    sa.Column('new_status', sa.String(length=50), nullable=True),
    sa.Column('old_vendor_name', sa.String(length=100), nullable=True),
    sa.Column('new_vendor_name', sa.String(length=100), nullable=True),
    sa.Column('old_total_cost', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('new_total_cost', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('old_odometer', sa.Integer(), nullable=True),
    sa.Column('new_odometer', sa.Integer(), nullable=True),
    sa.Column('remarks', sa.String(length=500), nullable=True),
    sa.Column('changed_by', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('clock_timestamp()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('clock_timestamp()'), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('delete_reason', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('version_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['changed_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['maintenance_id'], ['maintenances.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('payments',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('payment_number', sa.String(length=50), nullable=False),
    sa.Column('payment_type', sa.Enum('RECEIPT', 'DISBURSEMENT', name='payment_type_enum'), nullable=False),
    sa.Column('payment_mode', sa.Enum('CASH', 'UPI', 'BANK_TRANSFER', 'CARD', 'CHEQUE', 'CREDIT', 'OTHER', name='payment_mode_enum'), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('payment_date', sa.Date(), nullable=False),
    sa.Column('reference_number', sa.String(length=100), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('trip_id', sa.Uuid(), nullable=True),
    sa.Column('party_id', sa.Uuid(), nullable=True),
    sa.Column('driver_id', sa.Uuid(), nullable=True),
    sa.Column('expense_category_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('clock_timestamp()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('clock_timestamp()'), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('delete_reason', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('version_id', sa.Integer(), nullable=False),
    sa.CheckConstraint('(party_id IS NOT NULL) OR (driver_id IS NOT NULL) OR (trip_id IS NOT NULL) OR (expense_category_id IS NOT NULL)', name='chk_payments_target_not_empty'),
    sa.CheckConstraint('amount > 0', name='chk_payments_amount'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['driver_id'], ['drivers.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['expense_category_id'], ['expense_categories.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['party_id'], ['parties.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['trip_id'], ['trips.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payments_driver_id'), 'payments', ['driver_id'], unique=False)
    op.create_index(op.f('ix_payments_expense_category_id'), 'payments', ['expense_category_id'], unique=False)
    op.create_index(op.f('ix_payments_party_id'), 'payments', ['party_id'], unique=False)
    op.create_index(op.f('ix_payments_payment_number'), 'payments', ['payment_number'], unique=False)
    op.create_index(op.f('ix_payments_reference_number'), 'payments', ['reference_number'], unique=False)
    op.create_index(op.f('ix_payments_trip_id'), 'payments', ['trip_id'], unique=False)
    op.create_index('uq_payments_payment_number', 'payments', ['payment_number'], unique=True, postgresql_where='deleted_at IS NULL')
    op.create_table('trip_expenses',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('expense_number', sa.String(length=50), nullable=False),
    sa.Column('trip_id', sa.Uuid(), nullable=False),
    sa.Column('party_id', sa.Uuid(), nullable=True),
    sa.Column('paid_to_name', sa.String(length=100), nullable=True),
    sa.Column('expense_type', sa.Enum('DIESEL', 'DRIVER_ADVANCE', 'DRIVER_BATA', 'FOOD', 'TOLL', 'LOADING', 'UNLOADING', 'REPAIR', 'MAINTENANCE', 'TYRE', 'PERMIT', 'RTO', 'POLICE_FINE', 'PARKING', 'BROKER_COMMISSION', 'FUEL', 'OTHER', name='expense_type_enum'), nullable=False),
    sa.Column('expense_date', sa.Date(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('payment_mode', sa.Enum('CASH', 'UPI', 'BANK_TRANSFER', 'CARD', 'CHEQUE', 'CREDIT', 'OTHER', name='payment_mode_enum'), nullable=False),
    sa.Column('payment_status', sa.Enum('PAID', 'UNPAID', 'PARTIAL', 'SUCCESS', 'PENDING', 'FAILED', 'CANCELLED', name='payment_status_enum'), nullable=False),
    sa.Column('reference_number', sa.String(length=100), nullable=True),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('attachment_path', sa.String(length=500), nullable=True),
    sa.Column('attachment_name', sa.String(length=255), nullable=True),
    sa.Column('attachment_size', sa.Integer(), nullable=True),
    sa.Column('attachment_content_type', sa.String(length=100), nullable=True),
    sa.Column('created_ip', sa.String(length=45), nullable=True),
    sa.Column('updated_ip', sa.String(length=45), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('clock_timestamp()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('clock_timestamp()'), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('delete_reason', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('version_id', sa.Integer(), nullable=False),
    sa.CheckConstraint('amount > 0', name='chk_trip_expenses_amount'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['party_id'], ['parties.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['trip_id'], ['trips.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trip_expenses_expense_date'), 'trip_expenses', ['expense_date'], unique=False)
    op.create_index(op.f('ix_trip_expenses_expense_number'), 'trip_expenses', ['expense_number'], unique=False)
    op.create_index(op.f('ix_trip_expenses_expense_type'), 'trip_expenses', ['expense_type'], unique=False)
    op.create_index(op.f('ix_trip_expenses_party_id'), 'trip_expenses', ['party_id'], unique=False)
    op.create_index(op.f('ix_trip_expenses_trip_id'), 'trip_expenses', ['trip_id'], unique=False)
    op.create_index('uq_trip_expenses_number', 'trip_expenses', ['expense_number'], unique=True, postgresql_where='deleted_at IS NULL')
    op.create_table('fuel_histories',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('fuel_transaction_id', sa.UUID(), nullable=False),
    sa.Column('old_amount', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('new_amount', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('old_odometer', sa.Integer(), nullable=True),
    sa.Column('new_odometer', sa.Integer(), nullable=True),
    sa.Column('old_vendor_id', sa.UUID(), nullable=True),
    sa.Column('new_vendor_id', sa.UUID(), nullable=True),
    sa.Column('old_status', sa.Enum('DRAFT', 'VERIFIED', 'APPROVED', 'CANCELLED', name='fuel_transaction_status_enum'), nullable=True),
    sa.Column('new_status', sa.Enum('DRAFT', 'VERIFIED', 'APPROVED', 'CANCELLED', name='fuel_transaction_status_enum'), nullable=True),
    sa.Column('reason', sa.String(length=500), nullable=False),
    sa.Column('edited_by', sa.UUID(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('clock_timestamp()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('clock_timestamp()'), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('delete_reason', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('version_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['fuel_transaction_id'], ['fuel_transactions.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fuel_histories_fuel_transaction_id'), 'fuel_histories', ['fuel_transaction_id'], unique=False)
    op.create_table('invoice_payments',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('receipt_number', sa.String(length=30), nullable=False),
    sa.Column('invoice_id', sa.Uuid(), nullable=False),
    sa.Column('payment_date', sa.Date(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('payment_source', sa.Enum('CASH', 'BANK', 'UPI', 'CHEQUE', 'CARD', 'ONLINE', 'OTHER', name='payment_source_enum'), nullable=False),
    sa.Column('payment_status', sa.Enum('PAID', 'UNPAID', 'PARTIAL', 'SUCCESS', 'PENDING', 'FAILED', 'CANCELLED', name='payment_status_enum'), nullable=False),
    sa.Column('bank_name', sa.String(length=100), nullable=True),
    sa.Column('account_holder', sa.String(length=100), nullable=True),
    sa.Column('transaction_number', sa.String(length=100), nullable=True),
    sa.Column('cheque_number', sa.String(length=50), nullable=True),
    sa.Column('cheque_date', sa.Date(), nullable=True),
    sa.Column('reference_number', sa.String(length=100), nullable=True),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('attachment', sa.String(length=255), nullable=True),
    sa.Column('received_by', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('clock_timestamp()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('clock_timestamp()'), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('delete_reason', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('version_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], ),
    sa.ForeignKeyConstraint(['received_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_invoice_payments_created_at', 'invoice_payments', ['created_at'], unique=False)
    op.create_index('ix_invoice_payments_invoice_id', 'invoice_payments', ['invoice_id'], unique=False)
    op.create_index('ix_invoice_payments_payment_date', 'invoice_payments', ['payment_date'], unique=False)
    op.create_index('ix_invoice_payments_payment_source', 'invoice_payments', ['payment_source'], unique=False)
    op.create_index('ix_invoice_payments_payment_status', 'invoice_payments', ['payment_status'], unique=False)
    op.create_index('ix_invoice_payments_receipt_number', 'invoice_payments', ['receipt_number'], unique=True, postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_table('invoice_status_histories',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('invoice_id', sa.Uuid(), nullable=False),
    sa.Column('old_status', sa.String(length=50), nullable=True),
    sa.Column('new_status', sa.String(length=50), nullable=False),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('changed_by', sa.Uuid(), nullable=True),
    sa.Column('changed_at', sa.DateTime(timezone=True), server_default=sa.text('clock_timestamp()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('clock_timestamp()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('clock_timestamp()'), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('delete_reason', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('version_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['changed_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_invoice_status_histories_changed_by'), 'invoice_status_histories', ['changed_by'], unique=False)
    op.create_index(op.f('ix_invoice_status_histories_invoice_id'), 'invoice_status_histories', ['invoice_id'], unique=False)
    op.create_table('invoice_payment_history',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('payment_id', sa.Uuid(), nullable=False),
    sa.Column('old_amount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('new_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('old_status', sa.String(length=50), nullable=True),
    sa.Column('new_status', sa.String(length=50), nullable=False),
    sa.Column('old_payment_source', sa.String(length=50), nullable=True),
    sa.Column('new_payment_source', sa.String(length=50), nullable=False),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('changed_by', sa.Uuid(), nullable=True),
    sa.Column('changed_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('clock_timestamp()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('clock_timestamp()'), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('delete_reason', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('version_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['changed_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['payment_id'], ['invoice_payments.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )

    # Added circular foreign keys manually
    op.create_foreign_key(
        'fk_drivers_current_trip_id',
        'drivers', 'trips',
        ['current_trip_id'], ['id']
    )
    op.create_foreign_key(
        'fk_tractors_current_trip_id',
        'tractors', 'trips',
        ['current_trip_id'], ['id']
    )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('invoice_payment_history')
    op.drop_index(op.f('ix_invoice_status_histories_invoice_id'), table_name='invoice_status_histories')
    op.drop_index(op.f('ix_invoice_status_histories_changed_by'), table_name='invoice_status_histories')
    op.drop_table('invoice_status_histories')
    op.drop_index('ix_invoice_payments_receipt_number', table_name='invoice_payments', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_index('ix_invoice_payments_payment_status', table_name='invoice_payments')
    op.drop_index('ix_invoice_payments_payment_source', table_name='invoice_payments')
    op.drop_index('ix_invoice_payments_payment_date', table_name='invoice_payments')
    op.drop_index('ix_invoice_payments_invoice_id', table_name='invoice_payments')
    op.drop_index('ix_invoice_payments_created_at', table_name='invoice_payments')
    op.drop_table('invoice_payments')
    op.drop_index(op.f('ix_fuel_histories_fuel_transaction_id'), table_name='fuel_histories')
    op.drop_table('fuel_histories')
    op.drop_table('user_roles')
    op.drop_table('user_permissions')
    op.drop_index('uq_trip_expenses_number', table_name='trip_expenses', postgresql_where='deleted_at IS NULL')
    op.drop_index(op.f('ix_trip_expenses_trip_id'), table_name='trip_expenses')
    op.drop_index(op.f('ix_trip_expenses_party_id'), table_name='trip_expenses')
    op.drop_index(op.f('ix_trip_expenses_expense_type'), table_name='trip_expenses')
    op.drop_index(op.f('ix_trip_expenses_expense_number'), table_name='trip_expenses')
    op.drop_index(op.f('ix_trip_expenses_expense_date'), table_name='trip_expenses')
    op.drop_table('trip_expenses')
    op.drop_table('role_permissions')
    op.drop_index('uq_payments_payment_number', table_name='payments', postgresql_where='deleted_at IS NULL')
    op.drop_index(op.f('ix_payments_trip_id'), table_name='payments')
    op.drop_index(op.f('ix_payments_reference_number'), table_name='payments')
    op.drop_index(op.f('ix_payments_payment_number'), table_name='payments')
    op.drop_index(op.f('ix_payments_party_id'), table_name='payments')
    op.drop_index(op.f('ix_payments_expense_category_id'), table_name='payments')
    op.drop_index(op.f('ix_payments_driver_id'), table_name='payments')
    op.drop_table('payments')
    op.drop_table('maintenance_history')
    op.drop_index('uq_invoices_trip_id', table_name='invoices', postgresql_where='deleted_at IS NULL')
    op.drop_index('uq_invoices_invoice_number', table_name='invoices', postgresql_where='deleted_at IS NULL')
    op.drop_index(op.f('ix_invoices_trip_id'), table_name='invoices')
    op.drop_index(op.f('ix_invoices_status'), table_name='invoices')
    op.drop_index(op.f('ix_invoices_party_id'), table_name='invoices')
    op.drop_index(op.f('ix_invoices_invoice_number'), table_name='invoices')
    op.drop_index(op.f('ix_invoices_invoice_date'), table_name='invoices')
    op.drop_table('invoices')
    op.drop_index(op.f('ix_fuel_transactions_vendor_id'), table_name='fuel_transactions')
    op.drop_index(op.f('ix_fuel_transactions_trip_id'), table_name='fuel_transactions')
    op.drop_index(op.f('ix_fuel_transactions_tractor_id'), table_name='fuel_transactions')
    op.drop_index(op.f('ix_fuel_transactions_invoice_number'), table_name='fuel_transactions')
    op.drop_index(op.f('ix_fuel_transactions_fuel_number'), table_name='fuel_transactions')
    op.drop_index(op.f('ix_fuel_transactions_fuel_date'), table_name='fuel_transactions')
    op.drop_index(op.f('ix_fuel_transactions_driver_id'), table_name='fuel_transactions')
    op.drop_table('fuel_transactions')
    op.drop_index(op.f('ix_expenses_trip_id'), table_name='expenses')
    op.drop_index(op.f('ix_expenses_tractor_id'), table_name='expenses')
    op.drop_index(op.f('ix_expenses_category_id'), table_name='expenses')
    op.drop_index('idx_expenses_date', table_name='expenses')
    op.drop_table('expenses')
    op.drop_index(op.f('ix_user_sessions_user_id'), table_name='user_sessions')
    op.drop_index(op.f('ix_user_sessions_refresh_token_jti'), table_name='user_sessions')
    op.drop_table('user_sessions')
    op.drop_table('user_preferences')
    op.drop_index(op.f('ix_trip_status_histories_trip_id'), table_name='trip_status_histories')
    op.drop_table('trip_status_histories')
    op.drop_index('uq_settings_key', table_name='settings', postgresql_where='deleted_at IS NULL')
    op.drop_index(op.f('ix_settings_key'), table_name='settings')
    op.drop_table('settings')
    op.drop_index('uq_roles_name', table_name='roles', postgresql_where='deleted_at IS NULL')
    op.drop_index(op.f('ix_roles_name'), table_name='roles')
    op.drop_table('roles')
    op.drop_index(op.f('ix_refresh_tokens_token'), table_name='refresh_tokens')
    op.drop_table('refresh_tokens')
    op.drop_index('uq_quarries_name', table_name='quarries', postgresql_where='deleted_at IS NULL')
    op.drop_index(op.f('ix_quarries_name'), table_name='quarries')
    op.drop_table('quarries')
    op.drop_index('uq_permissions_name', table_name='permissions', postgresql_where='deleted_at IS NULL')
    op.drop_index(op.f('ix_permissions_name'), table_name='permissions')
    op.drop_table('permissions')
    op.drop_index(op.f('ix_password_history_user_id'), table_name='password_history')
    op.drop_table('password_history')
    op.drop_index('uq_parties_pan_number', table_name='parties', postgresql_where='pan_number IS NOT NULL AND deleted_at IS NULL')
    op.drop_index('uq_parties_mobile_number', table_name='parties', postgresql_where='deleted_at IS NULL')
    op.drop_index('uq_parties_gst_number', table_name='parties', postgresql_where='gst_number IS NOT NULL AND deleted_at IS NULL')
    op.drop_index(op.f('ix_parties_state'), table_name='parties')
    op.drop_index(op.f('ix_parties_party_type'), table_name='parties')
    op.drop_index(op.f('ix_parties_pan_number'), table_name='parties')
    op.drop_index(op.f('ix_parties_name'), table_name='parties')
    op.drop_index(op.f('ix_parties_mobile_number'), table_name='parties')
    op.drop_index(op.f('ix_parties_gst_number'), table_name='parties')
    op.drop_index(op.f('ix_parties_contact_person'), table_name='parties')
    op.drop_index(op.f('ix_parties_city'), table_name='parties')
    op.drop_table('parties')
    op.drop_index(op.f('ix_notifications_user_id'), table_name='notifications')
    op.drop_index('idx_notifications_unread', table_name='notifications', postgresql_where='read_at IS NULL')
    op.drop_table('notifications')
    op.drop_index('uq_materials_name', table_name='materials', postgresql_where='deleted_at IS NULL')
    op.drop_index(op.f('ix_materials_name'), table_name='materials')
    op.drop_table('materials')
    op.drop_index('idx_unique_maintenance_number', table_name='maintenances', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_index('idx_maintenance_type', table_name='maintenances')
    op.drop_index('idx_maintenance_tractor_id', table_name='maintenances')
    op.drop_index('idx_maintenance_status', table_name='maintenances')
    op.drop_index('idx_maintenance_scheduled_date', table_name='maintenances')
    op.drop_index('idx_maintenance_number', table_name='maintenances')
    op.drop_index('idx_maintenance_created_at', table_name='maintenances')
    op.drop_table('maintenances')
    op.drop_index(op.f('ix_login_history_user_id'), table_name='login_history')
    op.drop_table('login_history')
    op.drop_index(op.f('ix_fuel_vendors_vendor_code'), table_name='fuel_vendors')
    op.drop_index(op.f('ix_fuel_vendors_name'), table_name='fuel_vendors')
    op.drop_table('fuel_vendors')
    op.drop_index('uq_expense_categories_name', table_name='expense_categories', postgresql_where='deleted_at IS NULL')
    op.drop_index(op.f('ix_expense_categories_name'), table_name='expense_categories')
    op.drop_table('expense_categories')
    op.drop_index(op.f('ix_audit_logs_user_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_table_name'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_record_id'), table_name='audit_logs')
    op.drop_index('idx_audit_logs_target_record', table_name='audit_logs')
    op.drop_index('idx_audit_logs_created_at', table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index('uq_users_username', table_name='users', postgresql_where='deleted_at IS NULL')
    op.drop_index('uq_users_email', table_name='users', postgresql_where='deleted_at IS NULL')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index('uq_trips_trip_number', table_name='trips', postgresql_where='deleted_at IS NULL')
    op.drop_index(op.f('ix_trips_trip_number'), table_name='trips')
    op.drop_index(op.f('ix_trips_tractor_id'), table_name='trips')
    op.drop_index(op.f('ix_trips_status'), table_name='trips')
    op.drop_index(op.f('ix_trips_party_id'), table_name='trips')
    op.drop_index(op.f('ix_trips_driver_id'), table_name='trips')
    op.drop_table('trips')
    op.drop_index('uq_tractors_tractor_number', table_name='tractors', postgresql_where='deleted_at IS NULL')
    op.drop_index('uq_tractors_rc_number', table_name='tractors', postgresql_where='deleted_at IS NULL')
    op.drop_index(op.f('ix_tractors_tractor_number'), table_name='tractors')
    op.drop_index(op.f('ix_tractors_rc_number'), table_name='tractors')
    op.drop_index(op.f('ix_tractors_current_trip_id'), table_name='tractors')
    op.drop_table('tractors')
    op.drop_index('uq_drivers_license_number', table_name='drivers', postgresql_where='deleted_at IS NULL')
    op.drop_index('uq_drivers_employee_code', table_name='drivers', postgresql_where='deleted_at IS NULL')
    op.drop_index('uq_drivers_contact_phone', table_name='drivers', postgresql_where='deleted_at IS NULL')
    op.drop_index(op.f('ix_drivers_user_id'), table_name='drivers')
    op.drop_index(op.f('ix_drivers_license_number'), table_name='drivers')
    op.drop_index(op.f('ix_drivers_employee_code'), table_name='drivers')
    op.drop_index(op.f('ix_drivers_current_trip_id'), table_name='drivers')
    op.drop_table('drivers')

    # Added circular foreign keys manually
    op.create_foreign_key(
        'fk_drivers_current_trip_id',
        'drivers', 'trips',
        ['current_trip_id'], ['id']
    )
    op.create_foreign_key(
        'fk_tractors_current_trip_id',
        'tractors', 'trips',
        ['current_trip_id'], ['id']
    )

    # ### end Alembic commands ###
