"""create_fuel_management_module

Revision ID: bd0eb6cd646c
Revises: d43108e767b4
Create Date: 2026-07-13 18:21:36.546523

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bd0eb6cd646c'
down_revision: Union[str, Sequence[str], None] = 'd43108e767b4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Add FUEL to expense_type_enum explicitly before creating tables
    op.execute("ALTER TYPE expense_type_enum ADD VALUE IF NOT EXISTS 'FUEL'")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fuel_vendors',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('vendor_code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('contact_person', sa.String(length=255), nullable=True),
    sa.Column('mobile', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('gst_number', sa.String(length=50), nullable=True),
    sa.Column('address', sa.String(length=500), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('state', sa.String(length=100), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('opening_time', sa.Time(), nullable=True),
    sa.Column('closing_time', sa.Time(), nullable=True),
    sa.Column('is_company_owned', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.String(length=1000), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('clock_timestamp()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('clock_timestamp()'), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('version_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fuel_vendors_name'), 'fuel_vendors', ['name'], unique=False)
    op.create_index(op.f('ix_fuel_vendors_vendor_code'), 'fuel_vendors', ['vendor_code'], unique=True)
    op.create_table('fuel_transactions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('fuel_number', sa.String(length=50), nullable=False),
    sa.Column('tractor_id', sa.UUID(), nullable=False),
    sa.Column('trip_id', sa.UUID(), nullable=True),
    sa.Column('driver_id', sa.UUID(), nullable=False),
    sa.Column('vendor_id', sa.UUID(), nullable=False),
    sa.Column('station_type', sa.Enum('COMPANY', 'PRIVATE', 'MOBILE', 'OTHER', name='fuel_station_type_enum'), nullable=False),
    sa.Column('fuel_type', sa.Enum('DIESEL', 'PETROL', 'CNG', 'LNG', 'ELECTRIC', 'OTHER', name='fuel_type_enum'), nullable=False),
    sa.Column('fuel_date', sa.Date(), nullable=False),
    sa.Column('odometer', sa.Integer(), nullable=False),
    sa.Column('liters', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('rate_per_liter', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('previous_odometer', sa.Integer(), nullable=True),
    sa.Column('distance_since_last_fill', sa.Integer(), nullable=True),
    sa.Column('average_kmpl', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('payment_mode', sa.Enum('CASH', 'CARD', 'UPI', 'BANK_TRANSFER', 'FUEL_CARD', 'CREDIT', 'OTHER', name='fuel_payment_mode_enum'), nullable=False),
    sa.Column('invoice_number', sa.String(length=100), nullable=True),
    sa.Column('remarks', sa.String(length=1000), nullable=True),
    sa.Column('attachment', sa.String(length=500), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('is_full_tank', sa.Boolean(), nullable=False),
    sa.Column('fuel_card_number', sa.String(length=100), nullable=True),
    sa.Column('authorization_code', sa.String(length=100), nullable=True),
    sa.Column('transaction_reference', sa.String(length=255), nullable=True),
    sa.Column('is_suspicious', sa.Boolean(), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'VERIFIED', 'APPROVED', 'CANCELLED', name='fuel_transaction_status_enum'), nullable=False),
    sa.Column('gps_latitude', sa.Float(), nullable=True),
    sa.Column('gps_longitude', sa.Float(), nullable=True),
    sa.Column('gps_accuracy', sa.Float(), nullable=True),
    sa.Column('device_id', sa.String(length=100), nullable=True),
    sa.Column('location_address', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('clock_timestamp()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('clock_timestamp()'), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('version_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['driver_id'], ['drivers.id'], ),
    sa.ForeignKeyConstraint(['tractor_id'], ['tractors.id'], ),
    sa.ForeignKeyConstraint(['trip_id'], ['trips.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['vendor_id'], ['fuel_vendors.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fuel_transactions_driver_id'), 'fuel_transactions', ['driver_id'], unique=False)
    op.create_index(op.f('ix_fuel_transactions_fuel_date'), 'fuel_transactions', ['fuel_date'], unique=False)
    op.create_index(op.f('ix_fuel_transactions_fuel_number'), 'fuel_transactions', ['fuel_number'], unique=True)
    op.create_index(op.f('ix_fuel_transactions_invoice_number'), 'fuel_transactions', ['invoice_number'], unique=False)
    op.create_index(op.f('ix_fuel_transactions_tractor_id'), 'fuel_transactions', ['tractor_id'], unique=False)
    op.create_index(op.f('ix_fuel_transactions_trip_id'), 'fuel_transactions', ['trip_id'], unique=False)
    op.create_index(op.f('ix_fuel_transactions_vendor_id'), 'fuel_transactions', ['vendor_id'], unique=False)
    op.create_table('fuel_histories',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('fuel_transaction_id', sa.UUID(), nullable=False),
    sa.Column('old_amount', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('new_amount', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('old_odometer', sa.Integer(), nullable=True),
    sa.Column('new_odometer', sa.Integer(), nullable=True),
    sa.Column('old_vendor_id', sa.UUID(), nullable=True),
    sa.Column('new_vendor_id', sa.UUID(), nullable=True),
    sa.Column('old_status', sa.Enum('DRAFT', 'VERIFIED', 'APPROVED', 'CANCELLED', name='fuel_transaction_status_enum'), nullable=True),
    sa.Column('new_status', sa.Enum('DRAFT', 'VERIFIED', 'APPROVED', 'CANCELLED', name='fuel_transaction_status_enum'), nullable=True),
    sa.Column('reason', sa.String(length=500), nullable=False),
    sa.Column('edited_by', sa.UUID(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('clock_timestamp()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('clock_timestamp()'), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('version_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['fuel_transaction_id'], ['fuel_transactions.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fuel_histories_fuel_transaction_id'), 'fuel_histories', ['fuel_transaction_id'], unique=False)
    op.add_column('tractors', sa.Column('fuel_capacity', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tractors', 'fuel_capacity')
    op.drop_index(op.f('ix_fuel_histories_fuel_transaction_id'), table_name='fuel_histories')
    op.drop_table('fuel_histories')
    op.drop_index(op.f('ix_fuel_transactions_vendor_id'), table_name='fuel_transactions')
    op.drop_index(op.f('ix_fuel_transactions_trip_id'), table_name='fuel_transactions')
    op.drop_index(op.f('ix_fuel_transactions_tractor_id'), table_name='fuel_transactions')
    op.drop_index(op.f('ix_fuel_transactions_invoice_number'), table_name='fuel_transactions')
    op.drop_index(op.f('ix_fuel_transactions_fuel_number'), table_name='fuel_transactions')
    op.drop_index(op.f('ix_fuel_transactions_fuel_date'), table_name='fuel_transactions')
    op.drop_index(op.f('ix_fuel_transactions_driver_id'), table_name='fuel_transactions')
    op.drop_table('fuel_transactions')
    op.drop_index(op.f('ix_fuel_vendors_vendor_code'), table_name='fuel_vendors')
    op.drop_index(op.f('ix_fuel_vendors_name'), table_name='fuel_vendors')
    op.drop_table('fuel_vendors')
    # ### end Alembic commands ###
    
    op.execute("DROP TYPE IF EXISTS fuel_station_type_enum CASCADE")
    op.execute("DROP TYPE IF EXISTS fuel_type_enum CASCADE")
    op.execute("DROP TYPE IF EXISTS fuel_payment_mode_enum CASCADE")
    op.execute("DROP TYPE IF EXISTS fuel_transaction_status_enum CASCADE")
