"""create_maintenance_module

Revision ID: d43108e767b4
Revises: afa9143ad701
Create Date: 2026-07-13 17:47:42.720795

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd43108e767b4'
down_revision: Union[str, Sequence[str], None] = 'afa9143ad701'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('maintenances',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('maintenance_number', sa.String(length=50), nullable=False),
    sa.Column('tractor_id', sa.Uuid(), nullable=False),
    sa.Column('maintenance_type', postgresql.ENUM('ENGINE_SERVICE', 'GENERAL_SERVICE', 'BREAKDOWN', 'REPAIR', 'TYRE_CHANGE', 'BATTERY', 'INSURANCE', 'FITNESS', 'PERMIT', 'PUC', 'ENGINE_OVERHAUL', 'OIL_CHANGE', 'FILTER_CHANGE', 'BRAKE_SERVICE', 'CLUTCH', 'SUSPENSION', 'ELECTRICAL', 'BODY_WORK', 'OTHER', name='maintenance_type_enum'), nullable=False),
    sa.Column('priority', postgresql.ENUM('LOW', 'MEDIUM', 'HIGH', 'URGENT', name='maintenance_priority_enum'), nullable=False),
    sa.Column('status', postgresql.ENUM('SCHEDULED', 'IN_PROGRESS', 'COMPLETED', 'CANCELLED', name='maintenance_status_enum'), nullable=False),
    sa.Column('vendor_name', sa.String(length=100), nullable=True),
    sa.Column('vendor_mobile', sa.String(length=15), nullable=True),
    sa.Column('service_center', sa.String(length=150), nullable=True),
    sa.Column('invoice_number', sa.String(length=100), nullable=True),
    sa.Column('scheduled_date', sa.Date(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('completion_date', sa.Date(), nullable=True),
    sa.Column('next_service_date', sa.Date(), nullable=True),
    sa.Column('current_odometer', sa.Integer(), nullable=False),
    sa.Column('next_service_odometer', sa.Integer(), nullable=True),
    sa.Column('parts_cost', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('labor_cost', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('other_cost', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('total_cost', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('remarks', sa.String(length=500), nullable=True),
    sa.Column('attachment', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('clock_timestamp()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('clock_timestamp()'), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('version_id', sa.Integer(), nullable=False),
    sa.CheckConstraint('labor_cost >= 0', name='chk_maintenance_labor_cost'),
    sa.CheckConstraint('other_cost >= 0', name='chk_maintenance_other_cost'),
    sa.CheckConstraint('parts_cost >= 0', name='chk_maintenance_parts_cost'),
    sa.CheckConstraint('total_cost >= 0', name='chk_maintenance_total_cost'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tractor_id'], ['tractors.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_maintenance_created_at', 'maintenances', ['created_at'], unique=False)
    op.create_index('idx_maintenance_number', 'maintenances', ['maintenance_number'], unique=False)
    op.create_index('idx_maintenance_scheduled_date', 'maintenances', ['scheduled_date'], unique=False)
    op.create_index('idx_maintenance_status', 'maintenances', ['status'], unique=False)
    op.create_index('idx_maintenance_tractor_id', 'maintenances', ['tractor_id'], unique=False)
    op.create_index('idx_maintenance_type', 'maintenances', ['maintenance_type'], unique=False)
    op.create_index('idx_unique_maintenance_number', 'maintenances', ['maintenance_number'], unique=True, postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_table('maintenance_history',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('maintenance_id', sa.Uuid(), nullable=False),
    sa.Column('old_status', sa.String(length=50), nullable=True),
    sa.Column('new_status', sa.String(length=50), nullable=True),
    sa.Column('old_vendor_name', sa.String(length=100), nullable=True),
    sa.Column('new_vendor_name', sa.String(length=100), nullable=True),
    sa.Column('old_total_cost', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('new_total_cost', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('old_odometer', sa.Integer(), nullable=True),
    sa.Column('new_odometer', sa.Integer(), nullable=True),
    sa.Column('remarks', sa.String(length=500), nullable=True),
    sa.Column('changed_by', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('clock_timestamp()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('clock_timestamp()'), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('version_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['changed_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['maintenance_id'], ['maintenances.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('payments', sa.Column('payment_mode', sa.Enum('CASH', 'UPI', 'BANK_TRANSFER', 'CARD', 'CHEQUE', 'CREDIT', 'OTHER', name='payment_mode_enum'), nullable=False))
    
    tractor_status_enum = postgresql.ENUM('ACTIVE', 'IN_MAINTENANCE', 'OUT_OF_SERVICE', name='tractor_status_enum')
    tractor_status_enum.create(op.get_bind(), checkfirst=True)
    op.add_column('tractors', sa.Column('status', tractor_status_enum, nullable=False))
    
    op.add_column('tractors', sa.Column('current_odometer', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tractors', 'current_odometer')
    op.drop_column('tractors', 'status')
    op.execute("DROP TYPE IF EXISTS tractor_status_enum")
    op.drop_column('payments', 'payment_mode')
    op.drop_table('maintenance_history')
    op.drop_index('idx_unique_maintenance_number', table_name='maintenances', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_index('idx_maintenance_type', table_name='maintenances')
    op.drop_index('idx_maintenance_tractor_id', table_name='maintenances')
    op.drop_index('idx_maintenance_status', table_name='maintenances')
    op.drop_index('idx_maintenance_scheduled_date', table_name='maintenances')
    op.drop_index('idx_maintenance_number', table_name='maintenances')
    op.drop_index('idx_maintenance_created_at', table_name='maintenances')
    op.drop_table('maintenances')
    op.execute("DROP TYPE IF EXISTS maintenance_type_enum CASCADE")
    op.execute("DROP TYPE IF EXISTS maintenance_priority_enum CASCADE")
    op.execute("DROP TYPE IF EXISTS maintenance_status_enum CASCADE")
    # ### end Alembic commands ###
