"""alter_party_table_schema

Revision ID: e4295163b548
Revises: b67bcabd59a8
Create Date: 2026-07-13 15:15:04.170218

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e4295163b548'
down_revision: Union[str, Sequence[str], None] = 'b67bcabd59a8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('parties', sa.Column('mobile_number', sa.String(length=30), nullable=False, server_default=""))
    op.add_column('parties', sa.Column('alternate_mobile', sa.String(length=30), nullable=True))
    op.add_column('parties', sa.Column('email', sa.String(length=255), nullable=True))
    op.add_column('parties', sa.Column('gst_number', sa.String(length=15), nullable=True))
    op.add_column('parties', sa.Column('pan_number', sa.String(length=10), nullable=True))
    op.add_column('parties', sa.Column('address', sa.Text(), nullable=True))
    op.add_column('parties', sa.Column('city', sa.String(length=100), nullable=True))
    op.add_column('parties', sa.Column('state', sa.String(length=100), nullable=True))
    op.add_column('parties', sa.Column('pincode', sa.String(length=20), nullable=True))
    op.add_column('parties', sa.Column('opening_balance', sa.Numeric(precision=12, scale=2), nullable=False, server_default="0.00"))
    op.add_column('parties', sa.Column('credit_limit', sa.Numeric(precision=12, scale=2), nullable=False, server_default="0.00"))
    op.add_column('parties', sa.Column('remarks', sa.String(length=500), nullable=True))
    op.alter_column('parties', 'contact_person',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.drop_index(op.f('ix_parties_code'), table_name='parties')
    op.drop_index(op.f('ix_parties_tax_identifier'), table_name='parties')
    op.drop_index(op.f('uq_parties_code'), table_name='parties', postgresql_where='(deleted_at IS NULL)')
    op.drop_index(op.f('uq_parties_tax_identifier'), table_name='parties', postgresql_where='((tax_identifier IS NOT NULL) AND (deleted_at IS NULL))')
    op.create_index(op.f('ix_parties_city'), 'parties', ['city'], unique=False)
    op.create_index(op.f('ix_parties_contact_person'), 'parties', ['contact_person'], unique=False)
    op.create_index(op.f('ix_parties_gst_number'), 'parties', ['gst_number'], unique=False)
    op.create_index(op.f('ix_parties_mobile_number'), 'parties', ['mobile_number'], unique=False)
    op.create_index(op.f('ix_parties_pan_number'), 'parties', ['pan_number'], unique=False)
    op.create_index(op.f('ix_parties_party_type'), 'parties', ['party_type'], unique=False)
    op.create_index(op.f('ix_parties_state'), 'parties', ['state'], unique=False)
    op.create_index('uq_parties_gst_number', 'parties', ['gst_number'], unique=True, postgresql_where='gst_number IS NOT NULL AND deleted_at IS NULL')
    op.create_index('uq_parties_mobile_number', 'parties', ['mobile_number'], unique=True, postgresql_where='deleted_at IS NULL')
    op.create_index('uq_parties_pan_number', 'parties', ['pan_number'], unique=True, postgresql_where='pan_number IS NOT NULL AND deleted_at IS NULL')
    op.drop_column('parties', 'contact_email')
    op.drop_column('parties', 'contact_phone')
    op.drop_column('parties', 'billing_address')
    op.drop_column('parties', 'code')
    op.drop_column('parties', 'tax_identifier')
    op.drop_column('parties', 'outstanding_balance')
    op.drop_column('parties', 'payment_terms_days')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('parties', sa.Column('payment_terms_days', sa.INTEGER(), autoincrement=False, nullable=False, server_default="30"))
    op.add_column('parties', sa.Column('outstanding_balance', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=False, server_default="0.00"))
    op.add_column('parties', sa.Column('tax_identifier', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('parties', sa.Column('code', sa.VARCHAR(length=50), autoincrement=False, nullable=False, server_default=""))
    op.add_column('parties', sa.Column('billing_address', sa.TEXT(), autoincrement=False, nullable=False, server_default=""))
    op.add_column('parties', sa.Column('contact_phone', sa.VARCHAR(length=30), autoincrement=False, nullable=False, server_default=""))
    op.add_column('parties', sa.Column('contact_email', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_index('uq_parties_pan_number', table_name='parties', postgresql_where='pan_number IS NOT NULL AND deleted_at IS NULL')
    op.drop_index('uq_parties_mobile_number', table_name='parties', postgresql_where='deleted_at IS NULL')
    op.drop_index('uq_parties_gst_number', table_name='parties', postgresql_where='gst_number IS NOT NULL AND deleted_at IS NULL')
    op.drop_index(op.f('ix_parties_state'), table_name='parties')
    op.drop_index(op.f('ix_parties_party_type'), table_name='parties')
    op.drop_index(op.f('ix_parties_pan_number'), table_name='parties')
    op.drop_index(op.f('ix_parties_mobile_number'), table_name='parties')
    op.drop_index(op.f('ix_parties_gst_number'), table_name='parties')
    op.drop_index(op.f('ix_parties_contact_person'), table_name='parties')
    op.drop_index(op.f('ix_parties_city'), table_name='parties')
    op.create_index(op.f('uq_parties_tax_identifier'), 'parties', ['tax_identifier'], unique=True, postgresql_where='((tax_identifier IS NOT NULL) AND (deleted_at IS NULL))')
    op.create_index(op.f('uq_parties_code'), 'parties', ['code'], unique=True, postgresql_where='(deleted_at IS NULL)')
    op.create_index(op.f('ix_parties_tax_identifier'), 'parties', ['tax_identifier'], unique=False)
    op.create_index(op.f('ix_parties_code'), 'parties', ['code'], unique=False)
    op.alter_column('parties', 'contact_person',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.drop_column('parties', 'remarks')
    op.drop_column('parties', 'credit_limit')
    op.drop_column('parties', 'opening_balance')
    op.drop_column('parties', 'pincode')
    op.drop_column('parties', 'state')
    op.drop_column('parties', 'city')
    op.drop_column('parties', 'address')
    op.drop_column('parties', 'pan_number')
    op.drop_column('parties', 'gst_number')
    op.drop_column('parties', 'email')
    op.drop_column('parties', 'alternate_mobile')
    op.drop_column('parties', 'mobile_number')
    # ### end Alembic commands ###
