from enum import Enum


class ExpenseType(str, Enum):
    DIESEL = "DIESEL"
    DRIVER_ADVANCE = "DRIVER_ADVANCE"
    DRIVER_BATA = "DRIVER_BATA"
    FOOD = "FOOD"
    TOLL = "TOLL"
    LOADING = "LOADING"
    UNLOADING = "UNLOADING"
    REPAIR = "REPAIR"
    MAINTENANCE = "MAINTENANCE"
    TYRE = "TYRE"
    PERMIT = "PERMIT"
    RTO = "RTO"
    POLICE_FINE = "POLICE_FINE"
    PARKING = "PARKING"
    BROKER_COMMISSION = "BROKER_COMMISSION"
    OTHER = "OTHER"
